import type { MetroId } from "@karta/app";

/** A selected employment hub the pipeline computes drive-time to. */
export interface JobCenter {
  id: string;
  name: string;
  lat: number;
  lon: number;
  metroId?: MetroId;
}

/** Every selected job centre across all nine Gauteng metros and City of Cape Town. */
export const JOB_CENTERS = [
  {
    id: "pretoria-cbd",
    name: "Pretoria CBD",
    lat: -25.7461,
    lon: 28.1881,
    metroId: "tshwane",
  },
  {
    id: "menlyn",
    name: "Menlyn",
    lat: -25.7825,
    lon: 28.2775,
    metroId: "tshwane",
  },
  {
    id: "centurion",
    name: "Centurion",
    lat: -25.8603,
    lon: 28.1894,
    metroId: "tshwane",
  },
  {
    id: "rosslyn",
    name: "Rosslyn",
    lat: -25.6167,
    lon: 28.0833,
    metroId: "tshwane",
  },
  {
    id: "hatfield",
    name: "Hatfield",
    lat: -25.7487,
    lon: 28.2323,
    metroId: "tshwane",
  },
  {
    id: "waterkloof-brooklyn",
    name: "Waterkloof/Brooklyn",
    lat: -25.7677,
    lon: 28.2361,
    metroId: "tshwane",
  },
  {
    id: "pretoria-west",
    name: "Pretoria West",
    lat: -25.748,
    lon: 28.1428,
    metroId: "tshwane",
  },
  {
    id: "silverton-waltloo",
    name: "Silverton/Waltloo",
    lat: -25.7248,
    lon: 28.321,
    metroId: "tshwane",
  },
  {
    id: "johannesburg-cbd",
    name: "Johannesburg CBD",
    lat: -26.2041,
    lon: 28.0473,
    metroId: "johannesburg",
  },
  {
    id: "sandton",
    name: "Sandton",
    lat: -26.1076,
    lon: 28.0567,
    metroId: "johannesburg",
  },
  {
    id: "rosebank",
    name: "Rosebank",
    lat: -26.1467,
    lon: 28.0436,
    metroId: "johannesburg",
  },
  {
    id: "randburg",
    name: "Randburg",
    lat: -26.094,
    lon: 27.9761,
    metroId: "johannesburg",
  },
  {
    id: "roodepoort",
    name: "Roodepoort",
    lat: -26.1625,
    lon: 27.8727,
    metroId: "johannesburg",
  },
  {
    id: "midrand",
    name: "Midrand",
    lat: -25.9992,
    lon: 28.129,
    metroId: "johannesburg",
  },
  {
    id: "fourways",
    name: "Fourways",
    lat: -26.0104,
    lon: 28.0046,
    metroId: "johannesburg",
  },
  {
    id: "woodmead",
    name: "Woodmead",
    lat: -26.043,
    lon: 28.0975,
    metroId: "johannesburg",
  },
  {
    id: "germiston",
    name: "Germiston",
    lat: -26.2253,
    lon: 28.1676,
    metroId: "ekurhuleni",
  },
  {
    id: "kempton-park",
    name: "Kempton Park",
    lat: -26.104,
    lon: 28.2316,
    metroId: "ekurhuleni",
  },
  {
    id: "boksburg",
    name: "Boksburg",
    lat: -26.2118,
    lon: 28.2596,
    metroId: "ekurhuleni",
  },
  {
    id: "benoni",
    name: "Benoni",
    lat: -26.1885,
    lon: 28.3208,
    metroId: "ekurhuleni",
  },
  {
    id: "springs",
    name: "Springs",
    lat: -26.2507,
    lon: 28.4428,
    metroId: "ekurhuleni",
  },
  {
    id: "alberton",
    name: "Alberton",
    lat: -26.2679,
    lon: 28.1211,
    metroId: "ekurhuleni",
  },
  {
    id: "vereeniging-cbd",
    name: "Vereeniging CBD",
    lat: -26.6731,
    lon: 27.9314,
    metroId: "emfuleni",
  },
  {
    id: "vanderbijlpark-cbd",
    name: "Vanderbijlpark CBD",
    lat: -26.7052,
    lon: 27.8374,
    metroId: "emfuleni",
  },
  {
    id: "vanderbijlpark-se",
    name: "Vanderbijlpark SE",
    lat: -26.7124,
    lon: 27.8544,
    metroId: "emfuleni",
  },
  {
    id: "sebokeng-zone-6",
    name: "Sebokeng Zone 6",
    lat: -26.6003,
    lon: 27.8415,
    metroId: "emfuleni",
  },
  {
    id: "sharpeville",
    name: "Sharpeville",
    lat: -26.6898,
    lon: 27.8727,
    metroId: "emfuleni",
  },
  {
    id: "evaton",
    name: "Evaton",
    lat: -26.5196,
    lon: 27.8528,
    metroId: "emfuleni",
  },
  {
    id: "meyerton-cbd",
    name: "Meyerton CBD",
    lat: -26.559,
    lon: 28.0131,
    metroId: "midvaal",
  },
  {
    id: "de-deur",
    name: "De Deur",
    lat: -26.51,
    lon: 27.992,
    metroId: "midvaal",
  },
  {
    id: "henley-on-klip",
    name: "Henley on Klip",
    lat: -26.5141,
    lon: 28.0169,
    metroId: "midvaal",
  },
  {
    id: "walkerville",
    name: "Walkerville",
    lat: -26.376,
    lon: 27.947,
    metroId: "midvaal",
  },
  {
    id: "vaal-marina",
    name: "Vaal Marina",
    lat: -26.875,
    lon: 28.266,
    metroId: "midvaal",
  },
  {
    id: "golf-park",
    name: "Golf Park",
    lat: -26.5587,
    lon: 28.041,
    metroId: "midvaal",
  },
  {
    id: "heidelberg-cbd",
    name: "Heidelberg CBD",
    lat: -26.505,
    lon: 28.359,
    metroId: "lesedi",
  },
  {
    id: "ratanda",
    name: "Ratanda",
    lat: -26.523,
    lon: 28.401,
    metroId: "lesedi",
  },
  {
    id: "impumelelo",
    name: "Impumelelo",
    lat: -26.597,
    lon: 28.35,
    metroId: "lesedi",
  },
  {
    id: "nigel",
    name: "Nigel",
    lat: -26.431,
    lon: 28.477,
    metroId: "lesedi",
  },
  {
    id: "devon",
    name: "Devon",
    lat: -26.304,
    lon: 28.52,
    metroId: "lesedi",
  },
  {
    id: "endicott",
    name: "Endicott",
    lat: -26.576,
    lon: 28.423,
    metroId: "lesedi",
  },
  {
    id: "krugersdorp-cbd",
    name: "Krugersdorp CBD",
    lat: -26.096,
    lon: 27.775,
    metroId: "mogale-city",
  },
  {
    id: "chamdor",
    name: "Chamdor",
    lat: -26.113,
    lon: 27.8,
    metroId: "mogale-city",
  },
  {
    id: "kagiso",
    name: "Kagiso",
    lat: -26.168,
    lon: 27.787,
    metroId: "mogale-city",
  },
  {
    id: "munsieville",
    name: "Munsieville",
    lat: -26.086,
    lon: 27.753,
    metroId: "mogale-city",
  },
  {
    id: "magaliesburg",
    name: "Magaliesburg",
    lat: -26.001,
    lon: 27.55,
    metroId: "mogale-city",
  },
  {
    id: "muldersdrift",
    name: "Muldersdrift",
    lat: -26.007,
    lon: 27.848,
    metroId: "mogale-city",
  },
  {
    id: "randfontein-cbd",
    name: "Randfontein CBD",
    lat: -26.1758,
    lon: 27.702,
    metroId: "rand-west-city",
  },
  {
    id: "westonaria-cbd",
    name: "Westonaria CBD",
    lat: -26.319,
    lon: 27.649,
    metroId: "rand-west-city",
  },
  {
    id: "mohlakeng",
    name: "Mohlakeng",
    lat: -26.198,
    lon: 27.68,
    metroId: "rand-west-city",
  },
  {
    id: "bekkersdal",
    name: "Bekkersdal",
    lat: -26.353,
    lon: 27.73,
    metroId: "rand-west-city",
  },
  {
    id: "glenharvie",
    name: "Glenharvie",
    lat: -26.406,
    lon: 27.67,
    metroId: "rand-west-city",
  },
  {
    id: "simunye",
    name: "Simunye",
    lat: -26.398,
    lon: 27.62,
    metroId: "rand-west-city",
  },
  {
    id: "carletonville-cbd",
    name: "Carletonville CBD",
    lat: -26.3609,
    lon: 27.3977,
    metroId: "merafong-city",
  },
  {
    id: "khutsong",
    name: "Khutsong",
    lat: -26.401,
    lon: 27.347,
    metroId: "merafong-city",
  },
  {
    id: "fochville",
    name: "Fochville",
    lat: -26.488,
    lon: 27.493,
    metroId: "merafong-city",
  },
  {
    id: "kokosi",
    name: "Kokosi",
    lat: -26.435,
    lon: 27.467,
    metroId: "merafong-city",
  },
  {
    id: "wedela",
    name: "Wedela",
    lat: -26.396,
    lon: 27.365,
    metroId: "merafong-city",
  },
  {
    id: "welverdiend",
    name: "Welverdiend",
    lat: -26.351,
    lon: 27.275,
    metroId: "merafong-city",
  },
  {
    id: "cape-town-cbd",
    name: "Cape Town CBD",
    lat: -33.9249,
    lon: 18.4241,
    metroId: "cape-town",
  },
  {
    id: "bellville",
    name: "Bellville",
    lat: -33.9,
    lon: 18.6333,
    metroId: "cape-town",
  },
  {
    id: "century-city",
    name: "Century City",
    lat: -33.8917,
    lon: 18.5083,
    metroId: "cape-town",
  },
  {
    id: "claremont",
    name: "Claremont",
    lat: -33.9806,
    lon: 18.4653,
    metroId: "cape-town",
  },
  {
    id: "epping-industria",
    name: "Epping Industria",
    lat: -33.9342,
    lon: 18.5436,
    metroId: "cape-town",
  },
  {
    id: "montague-gardens",
    name: "Montague Gardens",
    lat: -33.8611,
    lon: 18.5214,
    metroId: "cape-town",
  },
  {
    id: "cape-town-airport",
    name: "Cape Town International Airport",
    lat: -33.9694,
    lon: 18.5972,
    metroId: "cape-town",
  },
] as const satisfies readonly JobCenter[];

/** Returns `JOB_CENTERS` filtered to one metro. */
export function getJobCentersForMetro(metroId: MetroId): JobCenter[] {
  return JOB_CENTERS.filter((jobCenter) => jobCenter.metroId === metroId);
}
