export const E2E = {
  panelToggle: "panel-toggle",
  panelContainer: "panel-container",
  panelSheetHandle: "panel-sheet-handle",
  panelViewport: "panel-viewport",
  panelLegend: "panel-legend",
  desktopLegend: "desktop-legend",
  mobileLegendTrigger: "mobile-legend-trigger",
  mobileLegendContent: "mobile-legend-content",
  dataLoadError: "data-load-error",
  retryDataLoad: "retry-data-load",
  settingsMenuTrigger: "settings-menu-trigger",
  settingsMenuContent: "settings-menu-content",
  languageToggle: "language",
  mapView: "map-view",
  locationSearchInput: "location-search-input",
  locationSearchResults: "location-search-results",
  locationSearchRetry: "location-search-retry",
  locationOutOfCoverage: "location-out-of-coverage",
  selectableFeatureSearch: "selectable-feature-search",
  selectableFeatureSearchInput: "selectable-feature-search-input",
  selectableFeatureSearchResults: "selectable-feature-search-results",
  basemapOption: {
    street: "basemap-option-street",
    satellite: "basemap-option-satellite",
    topo: "basemap-option-topo",
  },
  themeOption: {
    system: "theme-option-system",
    light: "theme-option-light",
    dark: "theme-option-dark",
  },
  layerToggle: {
    townships: "layer-toggle-townships",
    townshipsDescription: "layer-toggle-townships-description",
    nearestTransit: "layer-toggle-nearest-transit",
    rapidRail: "layer-toggle-rapid-rail",
    rapidRailError: "layer-toggle-rapid-rail-error",
  },
  panelTab: {
    layers: "panel-tab-layers",
    story: "panel-tab-story",
  },
  townshipPopup: "township-popup",
  locationContextMenu: "location-context-menu",
} as const;
