import { createGlobalThemeContract } from "@vanilla-extract/css";

/**
 * Typed, compile-time-checked view onto the Material 3 design tokens
 * documented in `docs/design-system.md` and generated by
 * `packages/web/scripts/generateM3Theme.ts` into `packages/web/src/index.css`.
 * @remarks Declares NO values and emits NO CSS — a host app defines every
 *   one of these custom properties itself. `index.css`'s dual
 *   `@media (prefers-color-scheme: dark)` + `:root[data-theme="dark"]`
 *   mechanism for light/dark switching is entirely its own;
 *   `createGlobalThemeContract` deliberately owns none of that. It exists
 *   only so a `.css.ts` file can reach `vars.color.primary` instead of
 *   hand-typing `"var(--md-sys-color-primary)"`, where a typo fails
 *   silently rather than at compile time. Every field is required to have
 *   no sensible generic fallback (unlike `@karta/map`'s own bespoke tokens
 *   — see `packages/map/src/theme/mapTokens.ts`), so none of these carry a
 *   `var(name, default)` form.
 */
export const vars = createGlobalThemeContract({
  color: {
    primary: "md-sys-color-primary",
    onPrimary: "md-sys-color-on-primary",
    primaryContainer: "md-sys-color-primary-container",
    onPrimaryContainer: "md-sys-color-on-primary-container",
    secondary: "md-sys-color-secondary",
    onSecondary: "md-sys-color-on-secondary",
    secondaryContainer: "md-sys-color-secondary-container",
    onSecondaryContainer: "md-sys-color-on-secondary-container",
    tertiary: "md-sys-color-tertiary",
    onTertiary: "md-sys-color-on-tertiary",
    tertiaryContainer: "md-sys-color-tertiary-container",
    onTertiaryContainer: "md-sys-color-on-tertiary-container",
    error: "md-sys-color-error",
    onError: "md-sys-color-on-error",
    errorContainer: "md-sys-color-error-container",
    onErrorContainer: "md-sys-color-on-error-container",
    background: "md-sys-color-background",
    onBackground: "md-sys-color-on-background",
    surface: "md-sys-color-surface",
    onSurface: "md-sys-color-on-surface",
    surfaceVariant: "md-sys-color-surface-variant",
    onSurfaceVariant: "md-sys-color-on-surface-variant",
    outline: "md-sys-color-outline",
    outlineVariant: "md-sys-color-outline-variant",
    surfaceContainerLowest: "md-sys-color-surface-container-lowest",
    surfaceContainerLow: "md-sys-color-surface-container-low",
    surfaceContainer: "md-sys-color-surface-container",
    surfaceContainerHigh: "md-sys-color-surface-container-high",
    surfaceContainerHighest: "md-sys-color-surface-container-highest",
    surfaceDim: "md-sys-color-surface-dim",
    surfaceBright: "md-sys-color-surface-bright",
    inverseSurface: "md-sys-color-inverse-surface",
    inverseOnSurface: "md-sys-color-inverse-on-surface",
    inversePrimary: "md-sys-color-inverse-primary",
    scrim: "md-sys-color-scrim",
    shadow: "md-sys-color-shadow",
    surfaceTint: "md-sys-color-surface-tint",
    /** Hand-written derived role (index.css), not one of the 37 roles `generateM3Theme.ts` generates. */
    surfaceContainerHover: "md-sys-color-surface-container-hover",
  },
  shape: {
    cornerNone: "md-sys-shape-corner-none",
    cornerExtraSmall: "md-sys-shape-corner-extra-small",
    cornerSmall: "md-sys-shape-corner-small",
    cornerMedium: "md-sys-shape-corner-medium",
    cornerLarge: "md-sys-shape-corner-large",
    cornerExtraLarge: "md-sys-shape-corner-extra-large",
    cornerFull: "md-sys-shape-corner-full",
  },
  elevation: {
    shadow1: "md-sys-elevation-shadow-1",
    shadow2: "md-sys-elevation-shadow-2",
    shadow3: "md-sys-elevation-shadow-3",
  },
  state: {
    hover: "state-hover",
    pressed: "state-pressed",
    selected: "state-selected",
  },
  motion: {
    durationShort: "motion-duration-short",
    durationMedium: "motion-duration-medium",
    easeStandard: "motion-ease-standard",
    easeDecelerate: "motion-ease-decelerate",
    easeAccelerate: "motion-ease-accelerate",
    easeSpring: "motion-ease-spring",
    easeLargeSurface: "motion-ease-large-surface",
  },
});

/** The shape of {@link vars} — every M3 token path this contract declares. */
export type M3Vars = typeof vars;
