import { createRequestHandler } from "react-router";
import { getAllKnownLayerIds } from "../src/analytics/knownLayerIds";
import type { AnalyticsEngineDataset } from "../src/analytics/layerUsage";
import { handleLayerUsageRequest } from "../src/analytics/layerUsage";
import { LAYER_USAGE_ENDPOINT } from "../src/constants/analyticsConfig";

const OLD_HOSTNAME = "buffer-zones.timothybrits.co.za";
const NEW_HOSTNAME = "karta.timothybrits.co.za";

/**
 * This Worker's Cloudflare bindings. `LAYER_USAGE` is optional — the
 * `analytics_engine_datasets` binding declared in `wrangler.jsonc` — so
 * local development or a preview environment without it configured still
 * runs; `handleLayerUsageRequest` treats a missing dataset as "don't record,
 * but still respond 204."
 * @remarks Hand-written rather than generated by `wrangler types`
 *   (`@cloudflare/workers-types` isn't a dependency) — this file is the only
 *   one that needs it, and isn't covered by `tsconfig.json` either way (see
 *   this module's own doc comment below).
 */
interface Env {
  LAYER_USAGE?: AnalyticsEngineDataset;
}

const requestHandler = createRequestHandler(
  () => import("../build/server/index.js"),
  import.meta.env?.MODE ?? "production",
);

/**
 * The Cloudflare Workers entry point. Permanently redirects requests for the
 * app's old hostname to its current one, handles `POST` requests to
 * `LAYER_USAGE_ENDPOINT` itself, then delegates everything else to the built
 * React Router server bundle.
 * @remarks Locale resolution (`paraglideMiddleware`) deliberately happens
 *   inside `entry.server.tsx`, not here, even though this file is also a
 *   valid place to call it. This file is bundled by wrangler (esbuild)
 *   directly from source, while `../build/server/index.js` is a separate
 *   artifact already bundled by Vite — two different bundlers, so
 *   `paraglide/runtime.js` (and its module-scope AsyncLocalStorage) ends up
 *   duplicated rather than shared between them. Wrapping here would resolve
 *   the locale into a copy of that state the render never reads from,
 *   leaving `getLocale()` inside the render permanently falling back to
 *   `baseLocale`. `entry.server.tsx` shares Vite's single build graph with
 *   `root.tsx`, so wrapping there is what actually reaches `getLocale()`.
 *   The layer-usage endpoint is handled here rather than as a React Router
 *   route for the same reason: a route module would need `env.LAYER_USAGE`
 *   threaded through a `RouterContextProvider`, another value that would
 *   silently end up duplicated rather than shared across the two bundlers.
 *   Its actual parse/validate/write logic lives in the framework-free
 *   `src/analytics/layerUsage.ts`, fully unit-testable and reachable from
 *   `src` (and so covered by `tsconfig.json`) — this handler is just the
 *   dispatch.
 */
export default {
  fetch(request: Request, env: Env) {
    const url = new URL(request.url);
    if (url.hostname === OLD_HOSTNAME) {
      url.hostname = NEW_HOSTNAME;
      return Response.redirect(url.toString(), 301);
    }
    if (url.pathname === LAYER_USAGE_ENDPOINT && request.method === "POST") {
      return handleLayerUsageRequest(
        request,
        env.LAYER_USAGE,
        getAllKnownLayerIds(),
      );
    }
    return requestHandler(request);
  },
} satisfies ExportedHandler<Env>;
