import type { MetaDescriptor } from "react-router";
import {
  OG_IMAGE_HEIGHT,
  OG_IMAGE_WIDTH,
  SITE_URL,
} from "./constants/siteConfig";
import { m } from "./paraglide/messages.js";
import { getLocale, locales } from "./paraglide/runtime.js";

/** Absolute URL of the Open Graph/Twitter card preview image, generated by `scripts/generateOgImage.ts`. */
const OG_IMAGE_URL = `${SITE_URL}/og-image.png`;

/**
 * Meta tags shared by every route regardless of its own title/description —
 * the OG image and its dimensions don't vary per page, and neither of these
 * is locale-dependent, so they're computed once rather than on every
 * `buildPageMeta` call.
 */
const STATIC_META_TAGS: MetaDescriptor[] = [
  {
    name: "viewport",
    content: "width=device-width, initial-scale=1.0, viewport-fit=cover",
  },
  { property: "og:type", content: "website" },
  { property: "og:image", content: OG_IMAGE_URL },
  { property: "og:image:width", content: String(OG_IMAGE_WIDTH) },
  { property: "og:image:height", content: String(OG_IMAGE_HEIGHT) },
  { name: "twitter:card", content: "summary_large_image" },
  { name: "twitter:image", content: OG_IMAGE_URL },
];

/** Fields of the `Dataset` JSON-LD block that don't vary by route or locale. */
const DATASET_JSON_LD_BASE = {
  "@context": "https://schema.org",
  "@type": "Dataset",
  license: "https://www.gnu.org/licenses/agpl-3.0.html",
  isAccessibleForFree: true,
  inLanguage: locales,
  spatialCoverage: {
    "@type": "Place",
    name: "Gauteng and Western Cape, South Africa",
  },
  keywords: [
    "apartheid spatial planning",
    "Gauteng",
    "Western Cape",
    "Cape Town",
    "township",
    "public transit access",
    "commute time",
    "South Africa",
    "urban planning",
  ],
} as const;

/**
 * Builds the full `<title>`/`<meta>` tag set for one route from its own
 * title, description, and canonical URL — including every Open Graph,
 * Twitter card, and Dataset JSON-LD tag derived from those three values.
 * @remarks Every route calls this directly with its own values, rather than
 *   exporting a `meta()` that only sets `title`/`description` and inheriting
 *   the rest from the root route via `matches`: React Router's per-route
 *   `meta()` replaces its parent's output entirely, and `title`/`description`
 *   aren't the only tags derived from a page's identity — `og:title`,
 *   `og:description`, `og:url`, `og:image:alt`, `twitter:title`,
 *   `twitter:description`, and the JSON-LD `name`/`description`/`url` all
 *   are too. A route that only patched the first two would leave the rest
 *   silently describing whichever route rendered first.
 */
export function buildPageMeta({
  title,
  description,
  url,
}: {
  title: string;
  description: string;
  url: string;
}): MetaDescriptor[] {
  const locale = getLocale();
  const alternateLocales = locales.filter((candidate) => candidate !== locale);

  return [
    { title },
    { name: "description", content: description },
    ...STATIC_META_TAGS,
    { property: "og:site_name", content: m.app_title() },
    { property: "og:title", content: title },
    { property: "og:description", content: description },
    { property: "og:url", content: url },
    { property: "og:locale", content: `${locale}_ZA` },
    ...alternateLocales.map((alternateLocale) => ({
      property: "og:locale:alternate",
      content: `${alternateLocale}_ZA`,
    })),
    { property: "og:image:alt", content: title },
    { name: "twitter:title", content: title },
    { name: "twitter:description", content: description },
    {
      "script:ld+json": {
        ...DATASET_JSON_LD_BASE,
        name: title,
        description,
        url,
      },
    },
  ];
}
